// Screenshot many scenes of the game canvas. usage: node tools/scenes.js outdir
const { chromium } = require('/opt/node22/lib/node_modules/playwright');
const path = require('path');
(async () => {
  const out = process.argv[2];
  const b = await chromium.launch();
  const p = await b.newPage({ viewport: { width: 400, height: 860 }, deviceScaleFactor: 2 });
  const logs = [];
  p.on('console', (m) => logs.push(m.type() + ': ' + m.text()));
  p.on('pageerror', (e) => logs.push('PAGEERROR: ' + e.message + '\n' + e.stack));
  await p.goto('file://' + path.resolve('index.html'));
  await p.waitForTimeout(700);
  await p.screenshot({ path: out + '/00_device.png' });
  const shot = async (name, js, wait = 600) => {
    if (js) await p.evaluate(js);
    await p.waitForTimeout(wait);
    const el = await p.$('#screen');
    await el.screenshot({ path: out + '/' + name + '.png' });
  };
  await shot('01_egg');
  await shot('02_hatch', "TM.game.s.pet.stageT = 999; ", 3500);
  await shot('03_baby_home', "", 2800);
  await shot('04_adult', "TM.game.grow(true); TM.game.grow(true); TM.game.s.pet.genes={color:'lemon',eyes:'kirakira',head:'kurukuru',body:'dress',back:'tenshi'}; TM.sc.go('home')", 800);
  await shot('05_menu', "TM.scenes.home.menu=true; TM.scenes.home.sel=1");
  await shot('06_status', "TM.sc.go('status')");
  await shot('06b_genes', "TM.scenes.status.page=2");
  await shot('07_food', "TM.sc.go('food'); TM.scenes.food.tab='snack'");
  await shot('08_eat', "TM.game.s.pet.hunger=1; TM.sc.go('eat',{food:TM.get('food','cake')})", 2300);
  await shot('09_bath', "TM.sc.go('bath')", 2000);
  await shot('10_toilet', "TM.game.s.pet.poops=[]; TM.sc.go('toilet')", 1500);
  await shot('11_clean', "TM.game.s.pet.poops=[{x:80,t:0},{x:100,t:0}]; TM.sc.go('toilet')", 700);
  await shot('12_toy', "TM.sc.go('toy'); TM.scenes.toy.list.i=0; TM.scenes.toy.btn('B')", 1500);
  await shot('13_game', "TM.sc.go('game')");
  await shot('14_outing', "TM.sc.go('outing')");
  await shot('15_travel', "TM.sc.go('travel',{to:'park'})", 1000);
  await shot('16_place', "TM.sc.go('place',{place:'park'})", 2500);
  await shot('17_beach', "TM.sc.go('place',{place:'beach'})", 2500);
  await shot('18_omiai', "TM.sc.go('omiai',{npc:TM.scenes.place.npc, place:'beach'})", 700);
  await shot('19_wedding', "TM.sc.go('wedding',{npc:TM.scenes.place.npc})", 4000);
  await shot('20_farewell', "", 3000);
  await shot('21_newegg', "", 2500);
  await shot('22_family', "TM.sc.go('family')");
  await shot('23_zukan', "TM.sc.go('zukan')");
  await shot('24_room_space', "TM.sc.go('room'); TM.scenes.room.i=3");
  await shot('25_room_wa', "TM.scenes.room.i=4");
  await shot('26_room_sweets', "TM.scenes.room.i=2");
  await shot('27_room_nat', "TM.scenes.room.i=1");
  await shot('28_sleep', "TM.game.grow(true);TM.game.grow(true);TM.game.grow(true);TM.game.s.clockOffset = 23 - new Date().getHours(); TM.sc.go('home')", 800);
  await shot('29_cafe', "TM.game.s.clockOffset=0; TM.game.s.pet.sleeping=false; TM.sc.go('place',{place:'cafe'})", 2500);
  await shot('30_garden', "TM.sc.go('place',{place:'garden'})", 2500);
  await p.click('#debugBtn');
  await p.waitForTimeout(300);
  await p.screenshot({ path: out + '/31_debug.png', fullPage: true });
  console.log(logs.join('\n'));
  await b.close();
})();
